name: Tauri Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Change directory into frontend
      run: cd frontend
    - uses: actions/checkout@v4
    - name: Build
      run: npm run build
    - name: Run Tauri build
      run: npx tauri build
