name: Tauri Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install prerequisites
      run: sudo apt update && sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
    - name: Install Node modules
      working-directory: frontend
      run: npm install --legacy-peer-deps
    - name: Build
      working-directory: frontend
      run: npm run build
    - name: Tauri build
      working-directory: frontend
      run: npx tauri build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release bundles
        path: frontend/src-tauri/target/release/bundle/
