name: Tauri Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install prerequisites
      working-directory: frontend
      run: npm install --legacy-peer-deps
    - name: Build
      working-directory: frontend
      run: npm run build
    - name: Tauri build
      working-directory: frontend
      run: npx tauri build
